# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: guess_who 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "guess_who".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["odina".freeze]
  s.date = "2017-10-14"
  s.description = "Extracts name from username or email".freeze
  s.email = "odina.abellana@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "files/females.txt",
    "files/initials.txt",
    "files/males.txt",
    "files/surnames.txt",
    "guess_who.gemspec",
    "lib/guess_who.rb",
    "lib/guess_who/comparator.rb",
    "lib/guess_who/names_loader.rb",
    "lib/guess_who/profiler.rb",
    "lib/guess_who/scorer.rb",
    "lib/guess_who/tokenizer.rb",
    "spec/lib/profiler_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/odina/guess_who".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.10".freeze
  s.summary = "Extract name from email".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<amatch>.freeze, ["~> 0.4.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.15"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.2.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<amatch>.freeze, ["~> 0.4.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.15"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.2.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<amatch>.freeze, ["~> 0.4.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.15"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.2.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

